version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    update_types:
      - "semver:minor"
      - "semver:patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    update_types:
      - "semver:major"
    labels:
      - "do-not-merge"
      - "dependencies"
