version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
    timezone: Asia/Calcutta
- package-ecosystem: npm
  directory: "/amundsen_application/static"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: urijs
    versions:
    - 1.19.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin-tslint"
    versions:
    - 4.9.1
  - dependency-name: "@babel/plugin-proposal-function-sent"
    versions:
    - 7.12.1
