version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
    timezone: Asia/Calcutta
- package-ecosystem: npm
  directory: "/amundsen_application/static"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
    timezone: Asia/Calcutta
