os: Visual Studio 2019
version: 4.1.0.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
install:
  - git clone https://github.com/etsy/statsd.git ..\statsd
  - ps: Start-Process "node" -ArgumentList "..\statsd\stats.js .\tests\JustEat.StatsD.Tests\statsdconfig.js" -WindowStyle Hidden
  - ps: .\SetAppVeyorBuildVersion.ps1
build_script:
  - ps: .\Build.ps1
after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "artifacts\coverage.cobertura.xml"
artifacts:
- path: '**\$(APPVEYOR_PROJECT_NAME)*.nupkg'
  name: Nuget
- path: artifacts\coverage*.xml
  name: 'Code Coverage'
test: off
