name: PR Auto Label
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: PR Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
