name: cd

on:
  push:
    branches: [ main ]

jobs:
  image:
    name: Build container image
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64]
        # linux/arm64 is disabled for now pending native runners; building in
        # qemu-aarch64 is too slow and costly.
        # See <https://github.com/actions/virtual-environments/issues/2187>
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit date
        id: author-date
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commit_details = await github.rest.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # Bump buildkit version because we need PR 2433 to fix a bug
          # in Github Actions Cache support.
          # See <https://github.com/moby/buildkit/pull/2433>
          driver-opts: image=moby/buildkit:v0.9.2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          load: true
          tags: ${{ github.repository }}:test
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            COMMIT_DATE=${{ steps.author-date.outputs.result }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
      - name: Test
        run:
          docker run --platform ${{ matrix.platform }} --rm ${{ github.repository }}:test --version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          push: true
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            COMMIT_DATE=${{ steps.author-date.outputs.result }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
