name: Check

on:
  push:
    branches: [ master ]

jobs:
  linux:
    name: Check latest commit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build on Ubuntu
        run: |
          ./boostrap.sh wk configure
          ./boostrap.sh wk build
