name: Closed Issue Message
on:
    issues:
        types: [closed]
jobs:
    auto_comment:
        runs-on: ubuntu-latest
        steps:
            - uses: aws-actions/closed-issue-message@v1
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  message: "This issue is now closed. Please be mindful that future comments are hard for our team to see."
