name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Build Debian Bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build
        run: |
          ./packaging/build compile-docker bookworm-amd64 .. ../build
