name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  linux:
    name: Build Debian Bookworm
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up the build environment
        run: ./bootstrap.sh tools setup

      - name: Build & package for all supported distros
        run: |
          meta/scripts/build-all.sh --flavore=stable

      - name: Upload Packages to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .cutekit/dist/*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
          prerelease: false
